# Generated by Django 4.2.3 on 2023-09-06 09:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coaches',
            name='working_time',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='График работы'),
        ),
    ]
